### ISSUE TITLE
error in densplot and getPlants

### ISSUE THREAD

**Issue by KateMMiller** [NCRN/NPSForVeg#108]
I get the following error when I try to run densplot. It's also causing issues with vegshiny when I try to compare growth stages with values=count. BA doesn't cause the same problem. It looks like it traces back to getPlants, but I'm not sure how to fix it. This happens for both MIDN and NETN, so isn't due to different plot sizes in NETN.

densplot(midn[[2]], group='trees', values='size',  years=2014:2017) returns the following error: 

 Error in if (group == "trees" | group == "saplings" | group == "shrubs") { : 
  missing value where TRUE/FALSE needed

**Comment by johnpauls** [comment]
Try densplot( midn[[2]], densargs=list(group="trees", values="size", years=2014:2017)

**Comment by KateMMiller** [comment]
Oh! I didn't realize I needed densargs=list(). Thanks for the correction.
