### ISSUE TITLE
Update import functions to include CWD

### ISSUE THREAD

**Issue by lizmatthews03** [NCRN/NPSForVeg#48]
importNCRN/ERMN/NETN/MIDN functions

**Comment by johnpauls** [comment]
List for Tracking

- [ ] MIDN

- [ ] ERMN

- [ ] MIDN

- [ ] NCRN

- [ ] NETN

- [ ] SHEN

- [ ] .csv import

**Comment by johnpauls** [comment]
This has been completed but issue was not closed.
